export type CropKey='corn'|'cassava'|'pineapple';export type ToolKey='hoe'|'seed'|'water'|'protect'|'harvest';export type GameMode='free'|'realistic';export type WeatherKey='sunny'|'cloudy'|'rain';export type BuildingKey='house'|'barn'|'market'|'workshop';export type MachineKey='irrigator'|'planter'|'harvester'
export interface CropDefinition{name:string;icon:string;seedCost:number;salePrice:number;baseYield:number;growMs:number;colors:string[]}
export interface PlotState{id:number;tilled:boolean;crop:CropKey|null;plantedAt:number;watered:boolean;protected:boolean}
export interface MachineState{owned:boolean;enabled:boolean;broken:boolean;condition:number}
export interface GameStats{tilled:number;planted:number;watered:number;harvested:number;sold:number;repaired:number}
export interface PlayerState{x:number;z:number;yaw:number}
export interface GameState{version:6;coins:number;level:number;barnLevel:number;barnCapacity:number;mode:GameMode;selectedTool:ToolKey;selectedCrop:CropKey;inventory:Record<CropKey,number>;plots:PlotState[];machines:Record<MachineKey,MachineState>;stats:GameStats;player:PlayerState;weather:WeatherKey;weatherChangedAt:number;lastSavedAt:number}
export const CROPS:Record<CropKey,CropDefinition>={corn:{name:'Milho',icon:'🌽',seedCost:4,salePrice:3,baseYield:3,growMs:70000,colors:['#8acb5a','#56a945','#f2c94c']},cassava:{name:'Mandioca',icon:'🌿',seedCost:8,salePrice:4,baseYield:5,growMs:105000,colors:['#78bf61','#408d4b','#b88b5a']},pineapple:{name:'Abacaxi',icon:'🍍',seedCost:15,salePrice:6,baseYield:6,growMs:150000,colors:['#65a953','#2f7d44','#e8ad39']}}
export const LEVELS=[{level:1,cost:0,multiplier:1,label:'Sítio Familiar'},{level:2,cost:150,multiplier:1.2,label:'Fazenda Organizada'},{level:3,cost:450,multiplier:1.4,label:'Fazenda Pecuária'},{level:4,cost:1200,multiplier:1.65,label:'Agroindústria'},{level:5,cost:3000,multiplier:1.95,label:'Fazenda Tecnológica'}]as const
export const BARNS=[{level:1,cost:0,capacity:10},{level:2,cost:100,capacity:20},{level:3,cost:350,capacity:35},{level:4,cost:900,capacity:55}]as const
export const MACHINES:Record<MachineKey,{name:string;icon:string;cost:number;unlockLevel:number;repairCost:number}>={irrigator:{name:'Irrigação automática',icon:'💧',cost:65,unlockLevel:1,repairCost:25},planter:{name:'Plantadeira',icon:'🚜',cost:120,unlockLevel:2,repairCost:40},harvester:{name:'Colheitadeira',icon:'⚙️',cost:240,unlockLevel:3,repairCost:70}}
const SAVE_KEY='agrofarm-3d-v6',emptyPlots=():PlotState[]=>Array.from({length:12},(_,id)=>({id,tilled:false,crop:null,plantedAt:0,watered:false,protected:false}))
export const createFreshState=():GameState=>({version:6,coins:100,level:1,barnLevel:1,barnCapacity:10,mode:'free',selectedTool:'hoe',selectedCrop:'corn',inventory:{corn:0,cassava:0,pineapple:0},plots:emptyPlots(),machines:{irrigator:{owned:false,enabled:false,broken:false,condition:100},planter:{owned:false,enabled:false,broken:false,condition:100},harvester:{owned:false,enabled:false,broken:false,condition:100}},stats:{tilled:0,planted:0,watered:0,harvested:0,sold:0,repaired:0},player:{x:0,z:8,yaw:180},weather:'sunny',weatherChangedAt:Date.now(),lastSavedAt:Date.now()})
export const loadState=():GameState=>{try{const parsed=JSON.parse(localStorage.getItem(SAVE_KEY)??'null')as Partial<GameState>|null;if(!parsed||parsed.version!==6)return createFreshState();const fresh=createFreshState();return{...fresh,...parsed,inventory:{...fresh.inventory,...parsed.inventory},machines:{irrigator:{...fresh.machines.irrigator,...parsed.machines?.irrigator},planter:{...fresh.machines.planter,...parsed.machines?.planter},harvester:{...fresh.machines.harvester,...parsed.machines?.harvester}},stats:{...fresh.stats,...parsed.stats},player:{...fresh.player,...parsed.player},plots:emptyPlots().map((plot,index)=>({...plot,...parsed.plots?.[index]}))}}catch{return createFreshState()}}
export const saveState=(state:GameState)=>{state.lastSavedAt=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(state))};export const resetState=()=>localStorage.removeItem(SAVE_KEY);export const usedStorage=(state:GameState)=>Object.values(state.inventory).reduce((total,amount)=>total+amount,0);export const currentLevel=(state:GameState)=>LEVELS.find(item=>item.level===state.level)??LEVELS[0];export const nextLevel=(state:GameState)=>LEVELS.find(item=>item.level===state.level+1);export const nextBarn=(state:GameState)=>BARNS.find(item=>item.level===state.barnLevel+1);export const growthProgress=(plot:PlotState,now=Date.now())=>plot.crop?Math.max(0,Math.min(1,(now-plot.plantedAt)/CROPS[plot.crop].growMs)):0
