const canvas = document.querySelector('#game');
const ctx = canvas.getContext('2d');
const $ = (s) => document.querySelector(s);
const ui = {
  coins: $('#coins'), level: $('#farm-level'), capacity: $('#capacity'), mode: $('#mode-button'),
  missionTitle: $('#mission-title'), missionText: $('#mission-text'), missionBar: $('#mission-bar'),
  interaction: $('#interaction'), interactionText: $('#interaction-text'), toast: $('#toast'),
  dialog: $('#dialog'), dialogContent: $('#dialog-content'), play: $('#play-button'), start: $('#start-screen'),
  action: $('#action-button'), joystick: $('#joystick'), stick: $('#stick'), menu: $('#menu-button')
};
const WORLD = { width: 1900, height: 1250 };
const KEY = 'agrofarm-organic-v4';
const CROPS = {
  corn: { name: 'Milho', icon: '🌽', cost: 4, sale: 3, yield: 3, grow: 70000, leaf: '#70a83d', fruit: '#f2c43b' },
  cassava: { name: 'Mandioca', icon: '🌿', cost: 8, sale: 4, yield: 5, grow: 105000, leaf: '#438c48', fruit: '#c49664' },
  pineapple: { name: 'Abacaxi', icon: '🍍', cost: 15, sale: 6, yield: 6, grow: 150000, leaf: '#3c8444', fruit: '#eab33a' }
};
const LEVELS = [{ level: 1, cost: 0, mult: 1 }, { level: 2, cost: 150, mult: 1.2 }, { level: 3, cost: 450, mult: 1.4 }, { level: 4, cost: 1200, mult: 1.6 }];
const BARNS = [{ level: 1, cost: 0, cap: 10 }, { level: 2, cost: 100, cap: 20 }, { level: 3, cost: 300, cap: 35 }];
const MACHINES = { irrigator: { name: 'Irrigador', icon: '💧', cost: 65, unlock: 1 }, planter: { name: 'Plantadeira', icon: '🚜', cost: 120, unlock: 2 }, harvester: { name: 'Colheitadeira', icon: '⚙️', cost: 240, unlock: 3 } };
const field = { x: 900, y: 250, cols: 5, rows: 4, w: 74, h: 58, gap: 10 };
const buildings = [
  { id: 'house', name: 'Casa da Fazenda', x: 180, y: 175, w: 310, h: 230, doorX: 337, doorY: 410 },
  { id: 'shop', name: 'Mercado Rural', x: 1370, y: 225, w: 280, h: 210, doorX: 1510, doorY: 440 },
  { id: 'barn', name: 'Galpão', x: 180, y: 790, w: 260, h: 190, doorX: 310, doorY: 985 },
  { id: 'workshop', name: 'Oficina', x: 1340, y: 790, w: 280, h: 190, doorX: 1480, doorY: 985 }
];
const trees = [[70,120],[120,220],[90,430],[95,650],[75,1060],[510,95],[610,145],[730,95],[1170,90],[1280,120],[1730,130],[1790,280],[1740,520],[1780,730],[1740,1030],[520,1090],[650,1130],[840,1090],[1100,1120],[1250,1080]];
const obstacles = buildings.map((b) => ({ x: b.x, y: b.y + 35, w: b.w, h: b.h - 35 }));
const makePlots = () => Array.from({ length: 20 }, (_, i) => ({ id: i, x: field.x + (i % field.cols) * (field.w + field.gap), y: field.y + Math.floor(i / field.cols) * (field.h + field.gap), tilled: false, crop: null, plantedAt: 0, watered: false, protected: false }));
function initialState() {
  return { version: 4, coins: 100, level: 1, barnLevel: 1, barnCapacity: 10, mode: 'free', selectedTool: 'hoe', selectedCrop: 'corn', inventory: { corn: 0, cassava: 0, pineapple: 0 }, plots: makePlots(), player: { x: 790, y: 720, dir: 'down' }, stats: { tilled: 0, planted: 0, harvested: 0, sold: 0 }, machines: Object.fromEntries(Object.keys(MACHINES).map((k) => [k, { owned: false, enabled: false, condition: 100, broken: false }])) };
}
function loadState() { try { const s = JSON.parse(localStorage.getItem(KEY)); if (s?.version !== 4) return initialState(); s.plots = makePlots().map((p, i) => ({ ...p, ...s.plots[i] })); return s; } catch { return initialState(); } }
let state = loadState(), running = false, active = null, now = Date.now(), last = performance.now(), cam = { x: 0, y: 0 }, keys = new Set(), joy = { x: 0, y: 0 }, toastTimer;
const clamp = (v, a, b) => Math.max(a, Math.min(b, v));
const distance = (a, b, c, d) => Math.hypot(a - c, b - d);
const usedCapacity = () => Object.values(state.inventory).reduce((a, b) => a + Number(b || 0), 0);
const levelData = () => LEVELS.find((x) => x.level === state.level) || LEVELS.at(-1);
const nextLevel = () => LEVELS.find((x) => x.level === state.level + 1);
const nextBarn = () => BARNS.find((x) => x.level === state.barnLevel + 1);
const save = () => localStorage.setItem(KEY, JSON.stringify(state));
function resize() { const d = Math.min(devicePixelRatio || 1, 2); canvas.width = innerWidth * d; canvas.height = innerHeight * d; canvas.style.width = `${innerWidth}px`; canvas.style.height = `${innerHeight}px`; ctx.setTransform(d, 0, 0, d, 0, 0); ctx.imageSmoothingEnabled = true; }
addEventListener('resize', resize); resize();
function toast(message) { clearTimeout(toastTimer); ui.toast.textContent = message; ui.toast.classList.remove('hidden'); toastTimer = setTimeout(() => ui.toast.classList.add('hidden'), 2500); }
function rr(x, y, w, h, r, fill, stroke, lw = 2) { ctx.beginPath(); ctx.roundRect(x, y, w, h, r); if (fill) { ctx.fillStyle = fill; ctx.fill(); } if (stroke) { ctx.strokeStyle = stroke; ctx.lineWidth = lw; ctx.stroke(); } }
function oval(x, y, rx, ry, fill) { ctx.fillStyle = fill; ctx.beginPath(); ctx.ellipse(x, y, rx, ry, 0, 0, Math.PI * 2); ctx.fill(); }
function shadow(x, y, rx, ry, alpha = .2) { oval(x, y, rx, ry, `rgba(42,63,32,${alpha})`); }
function flower(x, y, color) { ctx.fillStyle = '#4e9142'; ctx.fillRect(x - 1, y, 2, 8); ctx.fillStyle = color; for (let a = 0; a < 6; a++) { ctx.beginPath(); ctx.arc(x + Math.cos(a) * 4, y + Math.sin(a) * 4, 3, 0, Math.PI * 2); ctx.fill(); } ctx.fillStyle = '#e6b63e'; ctx.beginPath(); ctx.arc(x, y, 2, 0, Math.PI * 2); ctx.fill(); }
function path(points, width) { ctx.lineCap = 'round'; ctx.lineJoin = 'round'; ctx.strokeStyle = '#c99d67'; ctx.lineWidth = width; ctx.beginPath(); ctx.moveTo(...points[0]); for (let i = 1; i < points.length; i++) { const p = points[i - 1], q = points[i]; ctx.quadraticCurveTo(p[0], p[1], (p[0] + q[0]) / 2, (p[1] + q[1]) / 2); } ctx.lineTo(...points.at(-1)); ctx.stroke(); ctx.strokeStyle = 'rgba(255,233,179,.32)'; ctx.lineWidth = width * .18; ctx.stroke(); }
function drawGround() {
  ctx.fillStyle = '#76bc59'; ctx.fillRect(0, 0, WORLD.width, WORLD.height);
  for (let i = 0; i < 420; i++) { const x = (i * 137) % WORLD.width, y = (i * 83) % WORLD.height, r = 2 + i % 4; ctx.fillStyle = i % 3 ? '#8bca67' : '#5fa84c'; ctx.beginPath(); ctx.arc(x, y, r, 0, Math.PI * 2); ctx.fill(); }
  for (let i = 0; i < 65; i++) flower((i * 191) % WORLD.width, (i * 113 + 70) % WORLD.height, ['#fff3c4', '#f49ea7', '#f3d15b'][i % 3]);
  path([[-40,620],[300,590],[650,650],[980,620],[1300,560],[1940,610]],100); path([[340,620],[390,520],[350,410],[350,330]],60); path([[1510,600],[1490,500],[1510,430]],60); path([[310,650],[310,790]],60); path([[1470,650],[1470,790]],60); path([[780,625],[840,540],[860,425]],54);
  ctx.fillStyle = '#61b7cd'; ctx.beginPath(); ctx.moveTo(0,1080); ctx.bezierCurveTo(300,1010,470,1170,760,1095); ctx.bezierCurveTo(1050,1020,1370,1160,1900,1050); ctx.lineTo(1900,1250); ctx.lineTo(0,1250); ctx.closePath(); ctx.fill();
  rr(690,1060,210,70,18,'#9a653b','#714623',5); for (let x = 710; x < 890; x += 28) { ctx.fillStyle = '#c98b4e'; ctx.fillRect(x,1067,20,56); }
}
function drawFences() { ctx.strokeStyle = '#fff4cf'; ctx.lineWidth = 8; ctx.lineCap = 'round'; const seg = [[[850,205],[1360,205]],[[850,205],[850,575]],[[850,575],[1360,575]],[[1360,205],[1360,575]],[[515,760],[760,760]],[[515,760],[515,1010]],[[515,1010],[760,1010]],[[760,760],[760,1010]]]; for (const [a,b] of seg) { ctx.beginPath(); ctx.moveTo(...a); ctx.lineTo(...b); ctx.stroke(); } }
function tree(x, y, s = 1) { shadow(x + 6, y + 25, 38 * s, 14 * s, .18); rr(x - 10 * s, y - 4 * s, 20 * s, 50 * s, 8, '#765031'); const blobs = [[-18,-12,30,'#3d873f'],[16,-14,32,'#4a9846'],[0,-36,36,'#39813d'],[-4,8,30,'#56a64c']]; for (const [dx,dy,r,c] of blobs) oval(x + dx * s, y + dy * s, r * s, r * .82 * s, c); oval(x - 10 * s, y - 47 * s, 12 * s, 8 * s, '#76bd5b'); }
function roof(x,y,w,h,a,b){ctx.fillStyle=a;ctx.beginPath();ctx.moveTo(x-18,y+h);ctx.lineTo(x+w*.5,y);ctx.lineTo(x+w+18,y+h);ctx.closePath();ctx.fill();ctx.fillStyle=b;ctx.beginPath();ctx.moveTo(x+w*.5,y);ctx.lineTo(x+w+18,y+h);ctx.lineTo(x+w*.5,y+h);ctx.closePath();ctx.fill();}
function drawHouse(){const b=buildings[0];shadow(b.x+b.w/2,b.y+b.h+16,b.w*.52,22);rr(b.x,b.y+78,b.w,b.h-78,18,'#f2d49a','#99633b',4);roof(b.x,b.y,b.w,92,'#d55245','#b64339');rr(b.x+18,b.y+90,b.w-36,36,10,'#fff1c9');for(const x of [b.x+42,b.x+225])rr(x,b.y+142,48,52,10,'#91d0dc','#5d916f',3);rr(b.x+128,b.y+148,54,82,10,'#8b5634','#624027',3);ctx.fillStyle='#6a4228';ctx.font='900 17px system-ui';ctx.textAlign='center';ctx.fillText(`CASA LV ${state.level}`,b.x+b.w/2,b.y+116);}
function drawShop(){const b=buildings[1];shadow(b.x+b.w/2,b.y+b.h+14,b.w*.52,20);rr(b.x,b.y+58,b.w,b.h-58,18,'#efb567','#945b33',4);for(let i=0;i<8;i++){ctx.fillStyle=i%2?'#fff0bd':'#d75d49';ctx.fillRect(b.x+i*37-5,b.y+36,39,35);}rr(b.x+26,b.y+92,b.w-52,42,12,'#fff0be');ctx.fillStyle='#684126';ctx.font='900 19px system-ui';ctx.textAlign='center';ctx.fillText('MERCADO RURAL',b.x+b.w/2,b.y+120);rr(b.x+104,b.y+143,70,68,9,'#87542e','#624023',3);}
function drawBarn(){const b=buildings[2];shadow(b.x+b.w/2,b.y+b.h+12,b.w*.52,20);rr(b.x,b.y+55,b.w,b.h-55,18,'#c95343','#83352c',4);roof(b.x,b.y,b.w,70,'#964033','#7b332a');rr(b.x+83,b.y+85,94,105,10,'#f4dda2','#8b5734',4);ctx.fillStyle='#fff3be';ctx.font='900 16px system-ui';ctx.textAlign='center';ctx.fillText(`GALPÃO ${usedCapacity()}/${state.barnCapacity}`,b.x+b.w/2,b.y+78);}
function drawWorkshop(){const b=buildings[3];shadow(b.x+b.w/2,b.y+b.h+12,b.w*.52,20);rr(b.x,b.y+45,b.w,b.h-45,18,'#8ca0a3','#4f6265',4);rr(b.x-8,b.y+28,b.w+16,58,14,'#596e71');rr(b.x+28,b.y+112,78,58,10,'#dce6e3','#667f7a',3);rr(b.x+146,b.y+102,100,88,10,'#405154','#2e3c3e',3);ctx.fillStyle='#ffe17b';ctx.font='900 17px system-ui';ctx.textAlign='center';ctx.fillText('OFICINA',b.x+b.w/2,b.y+66);ctx.font='34px system-ui';ctx.fillText('⚙️',b.x+67,b.y+153);}
function cow(x,y,flip){shadow(x,y+25,31,8,.16);ctx.save();ctx.translate(x,y);if(flip)ctx.scale(-1,1);oval(0,0,28,18,'#fff6e5');ctx.fillStyle='#6b4a34';ctx.fillRect(-9,-14,14,12);ctx.fillRect(12,-8,11,13);oval(27,-4,12,10,'#fff6e5');ctx.fillStyle='#4a3a2f';ctx.fillRect(-18,14,5,18);ctx.fillRect(13,13,5,18);ctx.restore();}
function drawPasture(){rr(520,775,230,225,42,'#7bc05a','rgba(255,255,255,.25)',2);const t=performance.now()/1000;for(let i=0;i<3;i++)cow(565+i*62+Math.sin(t+i)*8,850+(i%2)*70,i%2);}
function cropProgress(p){return p.crop?clamp((now-p.plantedAt)/CROPS[p.crop].grow,0,1):0;}
function drawCrop(p){const c=CROPS[p.crop],pr=cropProgress(p),stage=pr<.25?1:pr<.55?2:pr<.85?3:4;for(let r=0;r<2;r++){for(let col=0;col<3;col++){const x=p.x+18+col*18,y=p.y+20+r*22;ctx.fillStyle=c.leaf;ctx.fillRect(x-2,y-stage*4,4,stage*5);for(let s=0;s<stage;s++){ctx.fillRect(x-7,y-s*5,6,3);ctx.fillRect(x+1,y-s*5-2,6,3);}if(stage===4){if(p.crop==='pineapple')oval(x,y-10,5,7,c.fruit);else if(p.crop==='corn'){ctx.fillStyle=c.fruit;ctx.fillRect(x+2,y-10,5,10);}else oval(x,y+3,4,6,c.fruit);}}}if(p.watered)oval(p.x+11,p.y+10,5,3,'#65bde0');if(p.protected){ctx.fillStyle='#ffe88a';ctx.fillRect(p.x+field.w-16,p.y+7,8,8);}if(pr>=1){ctx.strokeStyle='#fff0a0';ctx.lineWidth=4;ctx.strokeRect(p.x+4,p.y+4,field.w-8,field.h-8);}}
function drawField(){rr(field.x-36,field.y-46,field.cols*(field.w+field.gap)+58,field.rows*(field.h+field.gap)+72,34,'rgba(121,182,81,.36)','rgba(255,255,255,.22)',3);ctx.fillStyle='#fff7cf';ctx.font='900 16px system-ui';ctx.textAlign='left';ctx.fillText('HORTA PRINCIPAL',field.x,field.y-18);for(const p of state.plots){rr(p.x,p.y,field.w,field.h,18,p.tilled?'#8b5e39':'#83ba63',p.tilled?'#70462d':'#699e51',3);if(p.tilled){ctx.strokeStyle='#6f482e';ctx.lineWidth=2;for(let y=p.y+13;y<p.y+field.h-8;y+=11){ctx.beginPath();ctx.moveTo(p.x+10,y);ctx.lineTo(p.x+field.w-10,y);ctx.stroke();}}if(p.crop)drawCrop(p);}}
function drawPlayer(){const p=state.player,bob=Math.sin(performance.now()/100)*(keys.size?2:.3);ctx.save();ctx.translate(p.x,p.y+bob);shadow(0,24,18,7);rr(-13,-3,26,30,8,'#305d8a');oval(0,-18,13,15,'#e4b17f');ctx.fillStyle='#6e452d';ctx.beginPath();ctx.arc(0,-23,15,Math.PI,0);ctx.fill();ctx.fillStyle='#f2d76b';ctx.fillRect(-18,-34,36,7);ctx.fillStyle='#6c4c31';ctx.fillRect(-11,24,8,11);ctx.fillRect(3,24,8,11);ctx.restore();}
function drawWorld(){ctx.save();ctx.translate(-cam.x,-cam.y);drawGround();drawFences();trees.forEach(([x,y],i)=>tree(x,y,.9+(i%3)*.08));drawPasture();drawHouse();drawShop();drawBarn();drawWorkshop();drawField();drawPlayer();ctx.restore();}
function collides(x,y){if(x<20||y<20||x>WORLD.width-20||y>WORLD.height-20)return true;return obstacles.some((o)=>x>o.x-15&&x<o.x+o.w+15&&y>o.y-15&&y<o.y+o.h+15);}
function movement(){let x=0,y=0;if(keys.has('KeyA')||keys.has('ArrowLeft'))x--;if(keys.has('KeyD')||keys.has('ArrowRight'))x++;if(keys.has('KeyW')||keys.has('ArrowUp'))y--;if(keys.has('KeyS')||keys.has('ArrowDown'))y++;x+=joy.x;y+=joy.y;const l=Math.hypot(x,y);return l>1?{x:x/l,y:y/l}:{x,y};}
function update(dt){if(!running||!ui.dialog.classList.contains('hidden'))return;const v=movement(),speed=205;const nx=state.player.x+v.x*speed*dt,ny=state.player.y+v.y*speed*dt;if(!collides(nx,state.player.y))state.player.x=nx;if(!collides(state.player.x,ny))state.player.y=ny;cam.x+=(clamp(state.player.x-innerWidth/2,0,Math.max(0,WORLD.width-innerWidth))-cam.x)*.12;cam.y+=(clamp(state.player.y-innerHeight/2,0,Math.max(0,WORLD.height-innerHeight))-cam.y)*.12;}
function nearestPlot(){return state.plots.map((p)=>({...p,d:distance(state.player.x,state.player.y,p.x+field.w/2,p.y+field.h/2)})).filter((p)=>p.d<78).sort((a,b)=>a.d-b.d)[0];}
function detect(){const p=nearestPlot();if(p){active={type:'plot',id:p.id};ui.interactionText.textContent={hoe:'Preparar terreno',seed:`Plantar ${CROPS[state.selectedCrop].name}`,water:'Regar',protect:'Aplicar defensivo',hand:'Colher'}[state.selectedTool];ui.interaction.classList.remove('hidden');return;}const b=buildings.map((x)=>({...x,d:distance(state.player.x,state.player.y,x.doorX,x.doorY)})).filter((x)=>x.d<100).sort((a,b)=>a.d-b.d)[0];if(b){active={type:'building',id:b.id};ui.interactionText.textContent=`Entrar: ${b.name}`;ui.interaction.classList.remove('hidden');return;}active=null;ui.interaction.classList.add('hidden');}
function usePlot(p){const o=state.plots[p.id],tool=state.selectedTool;if(tool==='hoe'){if(o.crop)return toast('Há uma plantação aqui.');o.tilled=true;state.stats.tilled++;}else if(tool==='seed'){const c=CROPS[state.selectedCrop];if(!o.tilled)return toast('Prepare a terra primeiro.');if(o.crop)return toast('Este lote está ocupado.');if(state.coins<c.cost)return toast('Saldo insuficiente.');state.coins-=c.cost;o.crop=state.selectedCrop;o.plantedAt=Date.now();state.stats.planted++;}else if(tool==='water'){if(!o.crop)return toast('Nada plantado.');o.watered=true;}else if(tool==='protect'){if(!o.crop)return toast('Nada plantado.');if(state.coins<2)return toast('Faltam moedas.');state.coins-=2;o.protected=true;}else if(tool==='hand'){if(!o.crop)return toast('Nada para colher.');if(cropProgress(o)<1)return toast('Ainda não está pronto.');const c=CROPS[o.crop];let qty=c.yield+(o.watered?1:0)+(o.protected?1:0);qty=Math.min(qty,state.barnCapacity-usedCapacity());if(qty<=0)return toast('Galpão cheio.');state.inventory[o.crop]+=qty;state.stats.harvested+=qty;Object.assign(o,{crop:null,plantedAt:0,watered:false,protected:false,tilled:true});}save();hud();toast('Ação concluída.');}
function open(html){ui.dialogContent.innerHTML=html;ui.dialog.classList.remove('hidden');}
function close(){ui.dialog.classList.add('hidden');ui.dialogContent.innerHTML='';}
ui.dialog.addEventListener('click',(e)=>{if(e.target===ui.dialog||e.target.closest('.modal-close'))close();});
function enter(id){if(id==='shop'){const rows=Object.entries(CROPS).map(([k,c])=>`<div class="shop-item"><strong>${c.icon} ${c.name}</strong><small>${state.inventory[k]} unidades</small><button data-sell="${k}" ${!state.inventory[k]?'disabled':''}>Vender tudo</button></div>`).join('');open(`<button class="modal-close">×</button><h2>Mercado Rural</h2><div class="shop-grid">${rows}</div>`);}if(id==='house'){const n=nextLevel();open(`<button class="modal-close">×</button><h2>Casa da Fazenda</h2><p>Nível ${state.level} · lucro ${levelData().mult.toFixed(1)}x</p>${n?`<button class="primary" data-upgrade="house">Evoluir por ${n.cost}</button>`:''}`);}if(id==='barn'){const n=nextBarn();open(`<button class="modal-close">×</button><h2>Galpão</h2><p>${usedCapacity()}/${state.barnCapacity}</p>${n?`<button class="primary" data-upgrade="barn">Ampliar por ${n.cost}</button>`:''}`);}if(id==='workshop'){const rows=Object.entries(MACHINES).map(([k,m])=>`<div class="shop-item"><strong>${m.icon} ${m.name}</strong><small>${state.machines[k].owned?'Adquirida':`Libera no nível ${m.unlock}`}</small><button data-machine="${k}" ${state.level<m.unlock?'disabled':''}>${state.machines[k].owned?'Automatizar':`Comprar por ${m.cost}`}</button></div>`).join('');open(`<button class="modal-close">×</button><h2>Oficina</h2><div class="shop-grid">${rows}</div>`);}}
ui.dialog.addEventListener('click',(e)=>{const sell=e.target.dataset.sell;if(sell){const q=state.inventory[sell],gain=Math.round(q*CROPS[sell].sale*levelData().mult*100)/100;state.inventory[sell]=0;state.coins+=gain;state.stats.sold+=q;save();hud();enter('shop');}const up=e.target.dataset.upgrade;if(up==='house'){const n=nextLevel();if(!n||state.coins<n.cost)return toast('Saldo insuficiente.');state.coins-=n.cost;state.level=n.level;save();hud();close();}if(up==='barn'){const n=nextBarn();if(!n||state.coins<n.cost)return toast('Saldo insuficiente.');state.coins-=n.cost;state.barnLevel=n.level;state.barnCapacity=n.cap;save();hud();close();}const id=e.target.dataset.machine;if(id){const m=MACHINES[id],s=state.machines[id];if(!s.owned){if(state.coins<m.cost)return toast('Saldo insuficiente.');state.coins-=m.cost;s.owned=true;}else{s.enabled=!s.enabled;}save();hud();enter('workshop');}});
function interact(){if(!active)return;if(active.type==='plot')usePlot(state.plots[active.id]);else enter(active.id);}
function hud(){ui.coins.textContent=Number(state.coins).toFixed(2);ui.level.textContent=`LV ${state.level}`;ui.capacity.textContent=`${usedCapacity()}/${state.barnCapacity}`;ui.mode.textContent=state.mode==='free'?'Livre':'Realista';const s=state.stats;let title='Prepare seu primeiro terreno',text='Equipe a enxada e use perto de um lote.',pct=0;if(s.tilled){title='Plante sua primeira cultura';text='Escolha uma semente.';pct=25;}if(s.planted){title='Cuide da plantação';text='Regue e aplique defensivo.';pct=50;}if(s.harvested){title='Venda no mercado';text='Leve a colheita ao mercado.';pct=75;}if(s.sold){title='Expanda a fazenda';text='Evolua casa, galpão e máquinas.';pct=100;}ui.missionTitle.textContent=title;ui.missionText.textContent=text;ui.missionBar.style.width=`${pct}%`;}
document.querySelectorAll('.tool').forEach((b)=>b.addEventListener('click',()=>{document.querySelectorAll('.tool').forEach((x)=>x.classList.remove('active'));b.classList.add('active');state.selectedTool=b.dataset.tool;save();}));
document.querySelectorAll('.crop').forEach((b)=>b.addEventListener('click',()=>{document.querySelectorAll('.crop').forEach((x)=>x.classList.remove('selected'));b.classList.add('selected');state.selectedCrop=b.dataset.crop;save();}));
ui.mode.addEventListener('click',()=>{state.mode=state.mode==='free'?'realistic':'free';save();hud();});
ui.menu.addEventListener('click',()=>open('<button class="modal-close">×</button><h2>AgroFarm</h2><p>Use WASD ou setas. Aproxime-se e pressione E.</p>'));
addEventListener('keydown',(e)=>{keys.add(e.code);if(['KeyE','Space'].includes(e.code)){e.preventDefault();interact();}});addEventListener('keyup',(e)=>keys.delete(e.code));ui.action.addEventListener('click',interact);
let pointer=null;ui.joystick.addEventListener('pointerdown',(e)=>{pointer=e.pointerId;ui.joystick.setPointerCapture(pointer);});ui.joystick.addEventListener('pointermove',(e)=>{if(e.pointerId!==pointer)return;const r=ui.joystick.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,l=Math.hypot(x,y)||1,m=Math.min(36,l);joy={x:x/l,y:y/l};ui.stick.style.transform=`translate(${joy.x*m}px,${joy.y*m}px)`;});function release(){pointer=null;joy={x:0,y:0};ui.stick.style.transform='';}ui.joystick.addEventListener('pointerup',release);ui.joystick.addEventListener('pointercancel',release);
ui.play.addEventListener('click',()=>{running=true;ui.start.classList.add('hidden');});
function loop(t){const dt=Math.min(.033,(t-last)/1000);last=t;now=Date.now();update(dt);detect();drawWorld();hud();requestAnimationFrame(loop);}hud();requestAnimationFrame(loop);
if('serviceWorker'in navigator&&location.protocol==='https:')addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));